sudo: no

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

git:
    depth: 3

addons:
    apt:
        packages:
            - autoconf
            - automake
            - autopoint
            - libtool
            - gettext
            - flex
            - liblzma5
            - liblzma-dev
            - libidn2-0
            - libidn2-0-dev
            - libunistring0
            - valgrind

# Change this to your needs
script: ./.travis.sh
before_install:
  - echo $TRAVIS_OS_NAME
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnutls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nettle; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated autoconf || brew upgrade autoconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated automake || brew upgrade automake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated libtool || brew upgrade libtool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated gettext || brew upgrade gettext; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install flex; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libidn; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install lbzip2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force gettext; fi
