sudo: required
dist: trusty

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

git:
    depth: 3

addons:
    apt:
        packages:
            - autoconf
            - automake
            - autopoint
            - libtool
            - gettext
            - flex
            - liblzma5
            - liblzma-dev
            - libidn2-0
            - libidn2-0-dev
            - libunistring0
            - valgrind
            - lcov

# Change this to your needs
before_install:
  - echo $TRAVIS_OS_NAME
  - ./.travis_setup.sh
script: ./.travis.sh
after_success:
  - coveralls --include libwget/ --include src/ -e "libwget/<stdout>" -e lib/ -e tests/
